version: "3.8"

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrongPassword123#
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - taskboard_network
    restart: on-failure

  web-app:
    container_name: web_app
    build:
      dockerfile: ./TaskBoard.WebApp/Dockerfile
    ports:
      - 5000:80
    networks:
      - taskboard_network
    restart: on-failure

volumes:
  sqldata:
networks:
  taskboard_network:
    external: true
