version: '3.8'

services:
  mysql:
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - 3306
      - 33060
    networks:
      - my_network
    volumes:
      - data:/var/lib/mysql
    image: mysql

  wordpress:
    container_name: wordpress-website
    environment:
      - WORDPRESS_DB_HOST=mysql  # Updated to use the service name defined in the same compose file
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpressdb
    volumes:
      - wp-data:/var/www/html
    ports:
      - 80:80
    networks:
      - my_network
    image: wordpress

networks:
  my_network:
    external: true

volumes:
  data:
  wp-data:
